development:
  adapter: postgresql
  url: <%= ENV['SB_DATABSE_URL'] %>
  pool: 30

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5

production:
  adapter: postgresql
  url: <%= ENV['SB_DATABSE_URL'] %>
  pool: 30
