development:
  adapter: postgresql
  host: localhost
  database: spreadblood_dev
  user: spreadblood_dev
  password: spreadblood_dev
  pool: 30

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5

production:
  adapter: postgresql
  url: <%= ENV['SB_DATABASE_URL'] %>
  pool: 30
